---
title: "Data Report"
output: word_document
params:
  hbres: 
    label: "Heath board of residence"
    value: "Ayrshire & Arran"
    input: select
    choices: ["Ayrshire & Arran", "Borders", "Fife"]
---

```{r setup, include=FALSE}
library(dplyr)
library(readr)

# Set up global chunk options.
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)

# Read in the dataset. Change the file path if you save the data somewhere else.
borders_age <- read_csv("data/borders_inc_age.csv")

# Filter the data according to the parameter.
data_hbres <- borders_age %>% filter(HBRes == params$hbres)
```

## Summary of Data

```{r numberofcases}
cases <- sum(borders_age$HBRes == params$hbres, na.rm = TRUE)
```

```{r lengthofstay}
ave_los <- mean(data_hbres$LengthOfStay)
```

* There are **`r cases`** records in the dataset.

* The average length of stay is *`r ave_los`*.

<br>

## Number of Records split by Mangement of Patient (Kable)

```{r mop_kable}
library(knitr)
data_hbres_table <- data_hbres %>% count(ManagementofPatient)

CREATE A TABLE USING KABLE FUNCTION
```

<br>

## Number of Records split by Mangement of Patient (Flextable)

<br>

```{r mop_flextable}
library(flextable)
library(officer)

data_hbres_table <- data_hbres %>% count(ManagementofPatient)

# Set up some formatting for flextable to be applied to most tables
my_ft_format <- function(ft) {
  ft %>% 
    bold(MAKE THE HEADER BOLD) %>% 
    bg(MAKE THE HEADER FILLED COLOUR AS #964091) %>% 
    color(MAKE THE HEADER TEXT COLOUR AS WHITE) %>% 
    align(MAKE THE HEADER TEXT CENTRALISED) %>% 
    valign(MAKE ALL TEXT VERTICALLY CENTRALISED) %>% 
    padding(padding.top = 0, padding.bottom = 0, part = "all")
}

headings <- list("Management of Patient", "Number of Records")
names(headings) <- names(data_hbres_table)

flextable(data_hbres_table, theme_fun = NULL) %>% 
  my_ft_format() %>% 
  set_header_labels(values = headings) %>% 
  align(ALIGN THE BODY TEXT TO LEFT) %>% 
  border(FORMAT THE BORDER LINES AS REQUIRED) %>% 
  width(SET THE COLUMN WIDTH TO 1.57 INCHES)
```
